$localBin = $HOME/.local/bin
$scriptsDir = $HOME/.config/hypr/scripts
$hyprDir = $HOME/.config/hypr

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = /home/ahoefer/.config/hypr/scripts/xauthority &
exec-once = dbus-update-actvation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland DBUS_SESSION_BUS_ADDRESS &
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME &
exec-once = systemctl --user start xdg-desktop-portal-hyprland &
exec-once = qs -c noctalia-shell &
exec-once = $scriptsDir/touchpad -init

source = modules/colors.conf
source = /home/ahoefer/.config/hypr/monitors.conf
source = modules/env.conf
source = modules/input.conf
source = modules/layout.conf
source = modules/animations.conf
source = modules/keybinds.conf

source = modules/window_rules.conf
source = modules/workspace.conf

source = /home/ahoefer/.config/hypr/noctalia/noctalia-colors.conf
