#!/bin/bash
###
### location script for waybar and hyprlock
###    version 1.0
###

## vars
cache_dir="$HOME/.cache"
cache_file="$cache_dir/ip_cache.txt"
city=""

if [ ! -f "$cache_file" ]; then
	mkdir -p "$(dirname "$cache_file")" # Create .cache directory if it doesn't exist
	touch "$cache_file"
fi

last_modified=$(stat -c %Y "$cache_file")
current_date=$(date +%s)
time_diff=$((current_date - last_modified))
expiry_time=600
cached_data=$(<"$cache_file")

get_city () {
  response=$(curl -s ipinfo.io 2>/dev/null | jq -r '.country + ", " + .city' 2>/dev/null)
  [[ $response =~ "Eschborn" ]] && city="${response/Eschborn/"Cologne"}" || city=$response
  echo "$city" >"$cache_file"
}

## main
if [ $time_diff -gt $expiry_time ] || [ -z "$cached_data" ]; then
	get_city
else
  city=$cached_data
fi

echo "$city"
exit 0
