#!/bin/bash
hyprctl dispatch focusmonitor 0
sleep 0.4
kitty -T sptlrx -o font_size=14 -e sptlrx &
sleep 0.4
hyprctl dispatch focuswindow title:sptlrx
sleep 0.4
hyprctl dispatch movetoworkspace 5
sleep 0.4
hyprctl dispatch movecursortocorner 0
sleep 0.4
kitty -T spotify -o font_size=14 -e ncspot &
sleep 0.4
hyprctl dispatch splitratio +0.3
