#!/bin/bash

time=$(date +%Y-%m-%d-%H-%M-%S)
dir="$(xdg-user-dir PICTURES)/Screenshots"
file="Screenshot_${time}_${RANDOM}.png"

function getmenu() {
  echo "󰹑 screenshot desktop"
  echo "󰲎 screenshot area"
}

result=$(getmenu | wofi -I --show dmenu -c $HOME/.config/wofi/config -s $HOME/.config/wofi/style_screenshot.css --prompt "Screenshot")
case $result in
	"󰹑 screenshot desktop")
		sleep 1
		grimblast --notify save screen ${dir}/$file
		;;
	"󰲎 screenshot area")
		grimblast --notify save area ${dir}/$file
		;;
esac
exit 0
