#!/bin/bash
kitty -T ncmpcpp -o allow_remote_control=socket-only --listen-on unix:/tmp/mkitty -e ncmpcpp &
sleep 1 
kitty @ --to unix:/tmp/mkitty launch cava                                                   
kitty @ --to unix:/tmp/mkitty resize-window -m 'title:^cava' -i -30                           
