#!/usr/bin/env bash

# CMDs
host=$(hostnamectl hostname)

# Options with Icons and Text
options=("Lock" "Logout" "Reboot" "Shutdown")
icons=("" "󰿅" "󱄌" "")

# Rofi CMD
wofi_cmd() {
    options_with_icons=()
    for ((i = 0; i < ${#options[@]}; i++)); do
        options_with_icons+=("${icons[$i]} ${options[$i]}")
    done

    chosen_option=$(printf "%s\n" "${options_with_icons[@]}" | wofi --dmenu -c $HOME/.config/wofi/configpower -s $HOME/.config/wofi/power_style.css -i -p " $USER@$host" | awk '{print $1}')
  # Execute Command
  case $chosen_option in
      "")
          hyprlock
          ;;
      "󰿅")
          hyprctl dispatch exit 0
          ;;
      "󱄌")
          systemctl reboot
          ;;
      "")
          systemctl poweroff
          ;;
      *)
          echo "choose: $1"
          ;;
  esac
}

# Actions
wofi_cmd
