cursor #c6d0f5
cursor_text_color #a5adce

foreground            #c6d0f5
background            #303446
selection_foreground  #303446
selection_background  #85c1dc
url_color             #99d1db

color0   #292c3c
color1   #fb71a0
color2   #6ddb78
color3   #fff572
color4   #84c4d0
color5   #2d5c65
color6   #99d1db
color7   #d8e3e5
color8   #838c8e
color9   #ff9fc0
color10  #a5ffae
color11  #fff8a5
color12  #b3e7f0
color13  #c9f6ff
color14  #dcf9ff
color15  #f8fdff
