# rules
# windowrule                  = float, file_progress
# windowrule                  = float, confirm
# windowrule                  = float, dialog
# windowrule                  = float, download
# windowrule                  = float, notification
# windowrule                  = float, error
# windowrule                  = float, splash
# windowrule                  = float, confirmreset
# windowrule                  = float, galculator
# windowrule                  = float, hyprmixer
# windowrule                  = float, blueman-manager
windowrule {
  name = xdg-desktop-portal-gtk
  float = on
  match:class = (xdg-desktop-portal-gtk)$
}

windowrule {
  name = brave-browser
  opacity = 1.0 0.8
  match:class = ^(brave-browser)$
}

windowrule {
  name = kitty
  opacity = 0.9 0.5
  match:class = ^(kitty)$
}

windowrule {
  name = windowrule-6
  opacity = 0.9 0.7
  match:class = ^(main-dropterm)$
}

windowrule {
  name = spotify
  opacity = 0.9 0.7
  match:class = ^(Spotify)$
}

windowrule {
  name = floatkitty
  float = on
  size = (monitor_w*0.5) (monitor_h*0.5)
  center = on
  match:initial_title = ^(floatkitty)$
}

windowrule {
  name = sysinfo
  float = on
  opacity = 0.8 0.6
  size = 900 400
  center = on
  match:title = ^(sysinfo)$
}

windowrule {
  name = updater
  float = on
  size = 800 (monitor_h*0.94)
  move = ((monitor_w*1)-810) (49)
  opacity = 0.9 0.7
  match:initial_title = ^(update)$
}

windowrule {
  name = mpv
  float = on
  match:class = ^(mpv)$a
}

windowrule {
  name = ProtonUp-Qt
  float = on
  match:title = ^(ProtonUp-Qt - Wine/Proton Installer)$
}

windowrule {
  name = Bitwarden
  float = on
  match:title = ^(Bitwarden)$
}


# Steam Big Picture and Tower of Babel
windowrule {
  name = steam-tower-of-babel
  fullscreen = on
  match:class = (steam_app_2665680)$
}

# Steam Fullsreen Planet Crafter
windowrule {
  name = steam-planet-crafter
  fullscreen = yes
  match:class = (steam_app_1284190)
}

# Steam Fullsreen Planet Crafter
windowrule {
  name = steam-skyrim
  fullscreen = yes
  match:class = (steam_app_489830)
}

windowrule {
  name = Brave Save Dialog
  fullscreen = no
  float = on
  match:class = ^(brave)$
  match:title = ^(.*speichern.*)$
  center = on
}
