#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Nordic'
ICONS='BreezeX-Dark'
FONT='NotoSans Nerd Font 10'
CURSOR='Nordzy-cursors-white'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
	${SCHEMA} color-scheme 'prefer-dark'
}

apply_themes
