#!/bin/bash
hyprctl dispatch focusmonitor 0
sleep 0.3
kitty -T sptlrx -o font_size=12 -e sptlrx &
sleep 0.3
hyprctl dispatch focuswindow title:sptlrx
sleep 0.3
hyprctl dispatch movetoworkspace 9
sleep 0.3
hyprctl dispatch movecursortocorner 0
sleep 0.3
# kitty -T spotify -o font_size=12 -e spotify_player &
spotify &
sleep 1.5
hyprctl dispatch focuswindow title:sptlrx
sleep 0.3
hyprctl dispatch movecursortocorner 1
sleep 0.3
kitty -T cava -o font_size=12 -e cava &
sleep 0.3
hyprctl dispatch focuswindow title:sptlrx
sleep 0.3
hyprctl dispatch resizeactive 320 50%
