#!/bin/bash
monitor_list=$(hyprctl monitors | grep Monitor | awk '{print $2}')
monitor_count=$(echo "${monitor_list}" | wc -l)
if [[ $monitor_count -gt 2 ]]; then
  if [ ${monitor_list[@]} =~ "DP-3" ] && [ ${monitor_list[@]} =~ "DP-2" ]; then
    ln -snf $HOME/.config/hypr/monitors/DP23.conf $HOME/.config/hypr/monitor.conf
  fi
elif [[ $monitor_count -eq 2 ]]; then
  if [[ ${monitor_list[@]} =~ "DP-3" ]]; then
    ln -snf $HOME/.config/hypr/monitors/DP3.conf $HOME/.config/hypr/monitor.conf
  elif [[ ${monitor_list[@]} =~ "DP-2" ]]; then
    ln -snf $HOME/.config/hypr/monitors/DP2.conf $HOME/.config/hypr/monitor.conf
  elif [[ ${monitor_list[@]} =~ "DP-1" ]]; then
    ln -snf $HOME/.config/hypr/monitors/DP1.conf $HOME/.config/hypr/monitor.conf
  fi
else
  ln -snf $HOME/.config/hypr/monitors/eDP1.conf $HOME/.config/hypr/monitor.conf
fi
exit 0
