#!/bin/bash
currenttheme=$(cat "$HOME/.config/flavor")
SCHEMA='gsettings set org.gnome.desktop.interface'
monitors=$(hyprctl monitors | grep "Monitor" | wc -l)

if [ $# -eq 0 ]
then
  echo "{ \"text\": \"themes\", \"alt\": \"${currenttheme}\" }"
  exit 0
else
  case $currenttheme in
    "latte")
      THEME='catppuccin-frappe-blue-standard+default'
      ICONS='Papirus-Dark'
      SCHEME='prefer-dark'
      CSS="frappe"
      ;;
    "frappe")
      THEME='catppuccin-latte-blue-standard+default'
      ICONS='Papirus-Light'
      SCHEME='prefer-light'
      CSS="latte"
      ;;
  esac

  echo "${CSS}" > "$HOME/.config/flavor"
  spicetify config color_scheme "${CSS}"
  spicetify apply
 	"${SCHEMA}" gtk-theme "$THEME"
  "${SCHEMA}" icon-theme "$ICONS"
  "${SCHEMA}" color-scheme "$SCHEME"
  ln -sf "$HOME/.config/hypr/${CSS}.conf" "$HOME/.config/hypr/colors.conf"
  ln -sf "$HOME/.config/waybar/${CSS}.css" "$HOME/.config/waybar/color.css"
  ln -sf "$HOME/.config/rofi/${CSS}.rasi" "$HOME/.config/rofi/colors.rasi"
  ln -sf "$HOME/.config/swaync/${CSS}.css" "$HOME/.config/swaync/style.css"
  ln -sf "$HOME/.config/cava/${CSS}" "$HOME/.config/cava/config"
  ln -sf "$HOME/.config/clipse/${CSS}.json" "$HOME/.config/clipse/custom_theme.json"
  kitty +kitten themes --reload-in=all "catppuccin-${CSS}"
  killall -SIGUSR2 waybar
  killall -SIGURS1 cava
  kvantummanager --set "catppuccin-${CSS}-blue"
  for ((i=1; i<=monitors; i++)); do
    swaync-client --reload-css
  done
  notify-send -t 60000 "ThemeSwitcher" "Theme Switched to ${CSS}"
fi
