#!/bin/bash

TOUCHDEVICE="syna32b9:00-06cb:ce7d-"

if [ -z "$XDG_RUNTIME_DIR" ]; then
  export XDG_RUNTIME_DIR=/run/user/$(id -u)
fi

export STATUS_FILE="$XDG_RUNTIME_DIR/touchpad.status"

if [ ! -f "$STATUS_FILE" ]; then
  touch $STATUS_FILE
fi

enable_touchpad() {
  printf "true" > "$STATUS_FILE"
  notify-send -u normal "Enabling Touchpad"
  hyprctl keyword "device[${TOUCHDEVICE}touchpad]:enabled" true
  hyprctl keyword "device[${TOUCHDEVICE}mouse]:enabled" true
}

disable_touchpad() {
  printf "false" > "$STATUS_FILE"
  notify-send -u normal "Disabling Touchpad"
  hyprctl keyword "device[${TOUCHDEVICE}touchpad]:enabled" false
  hyprctl keyword "device[${TOUCHDEVICE}mouse]:enabled" false
}

if [ $# -gt 0 ]; then
  case $1 in
    "-init")
      disable_touchpad
      exit 0
      ;;
    "-get")
      [[ "$(cat "$STATUS_FILE")" = "true" ]] && echo "󰍾" || echo "󰍽"
      exit 0
      ;;
  esac
fi

if [ "$(cat "$STATUS_FILE")" = "true" ]; then
  disable_touchpad
elif [ "$(cat "$STATUS_FILE")" = "false" ]; then
  enable_touchpad
fi
 
