#!/bin/bash
function getpics() {
  DIR=$HOME/Bilder/wallpapers/
  cd $DIR
  PICS=$(ls -d ${DIR}*)
  cd
  for i in $PICS; do
    NAME=$(echo ${i} | tr '/' '\n' | tail -n1)
    echo "img:${i}:text:${NAME}"
  done
}

wallpaper=$(getpics | wofi -I -c $HOME/.config/wofi/config_wall -s $HOME/.config/wofi/style_wall.css)
walltoset=$(echo "$wallpaper" | awk -F':' '{print $2}')

swww img -t grow --transition-duration 2 ${walltoset} & disown
notify-send -a swww -u normal -i ${walltoset} "wallpaper changed"
