#!/bin/bash

DIR=$HOME/Bilder/wallpapers/
PICS=($(ls ${DIR}))
RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}
TRANSITION=( fade left right top bottom wipe wave grow center outer )
TRANSID=$(shuf -i 0-9 -n 1)

swww img -t ${TRANSITION[$TRANSID]} --transition-duration 2 ${DIR}${RANDOMPICS}
notify-send "${RANDOMPICS}"
