#!/bin/bash

TOUCHDEVICE="asup1205:00-093a:2008-touchpad"

if [ -z "$XDG_RUNTIME_DIR" ]; then
  export XDG_RUNTIME_DIR=/run/user/$(id -u)
fi

export STATUS_FILE="$XDG_RUNTIME_DIR/touchpad.status"

if [ ! -f "$STATUS_FILE" ]; then
  touch $STATUS_FILE
fi

enable_touchpad() {
  echo -n "true" > "$STATUS_FILE"
  notify-send -u normal "Enabling Touchpad"
  echo "return true" > $HOME/.config/hypr/touchpad.lua
  hyprctl reload
}

disable_touchpad() {
  echo -n "false" > "$STATUS_FILE"
  notify-send -u normal "Disabling Touchpad"
  echo "return false" > $HOME/.config/hypr/touchpad.lua
  hyprctl reload
}

if [ $# -gt 0 ]; then
  case $1 in
    "-init")
      disable_touchpad
      exit 0
      ;;
  esac
fi

if [ "$(cat "$STATUS_FILE")" = "true" ]; then
  disable_touchpad
elif [ "$(cat "$STATUS_FILE")" = "false" ]; then
  enable_touchpad
fi
