#!/bin/bash

###
# Wallpaper Selection Script for Rofi
###

# Set some variables
wall_dir="${HOME}/Bilder/wallpapers"
cacheDir="${HOME}/.cache/jp"
rofi_command="rofi -dmenu -theme ${HOME}/.config/rofi/wallpaper.rasi -theme-str ${rofi_override}"

# Create cache dir if not exists
if [ ! -d "${cacheDir}" ]; then
	mkdir -p "${cacheDir}"
fi

physical_monitor_size=24
monitor_res=$(hyprctl monitors | grep -A2 Monitor | head -n 2 | awk '{print $1}' | grep -oE '^[0-9]+')
dotsperinch=$(echo "scale=2; $monitor_res / $physical_monitor_size" | bc | xargs printf "%.0f")
monitor_res=$(($monitor_res * $physical_monitor_size / $dotsperinch))

rofi_override="element-icon{size:${monitor_res}px;border-radius:0px;}"

# Convert images in directory and save to cache dir
for imagen in "$wall_dir"/*; do
	if [ -f "$imagen" ] || [ -L "$imagen" ]; then
		if [ -L "$imagen" ]; then
			imagepath=${wall_dir}/$(readlink "$imagen")
		else
			imagepath=$imagen
		fi
		imagename=$(basename "$imagepath")
		if [ ! -f "${cacheDir}/${imagename}" ]; then
			magick -strip "$imagepath" -thumbnail 500x500^ -gravity center -extent 500x500 "${cacheDir}/${imagename}"
		fi
	fi
done

# Select a picture with rofi
wall_selection=$(find -L "${wall_dir}" -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) -exec basename {} \; | sort | while read -r A; do echo -en "$A\x00icon\x1f""${cacheDir}"/"$A\n"; done | $rofi_command)

# Set the wallpaper
[[ -n "$wall_selection" ]] || exit 1
swww img -t grow --transition-duration 2 ${wall_dir}/${wall_selection}
notify-send -a swww -u normal -i ${wall_dir}/${wall_selection} "wallpaper changed"

exit 0
