cookie: "sp_t=a7a2199dd56676b2e95555c63580cd1f; sp_dc=AQDkngz0Wwl4JVptSjqadLn-ku4cFS0n8iZvUDGaN2uywheNr9k5sD5O_iHtghuievtp1sJoZh0beCLiqGafAIoqRZozitxXnS3XoQvGjc0sIIjX6wamB89OXvhvWZixA1WP-0QJSYbBvuIpq4Q6xcZG2wspaJU; sp_key=c5097c02-e9ac-46f5-a073-4d2c79559cc3; sp_m=de; OptanonAlertBoxClosed=2024-02-21T08:21:01.340Z; eupubconsent-v2=CP6U9VgP6U9VgAcABBENAoEgAP_AAAAAAAYgg1QiIAAgAEAASABQAFwAPABAACsAFwAbAA7AB8AIgASAAoABUAC6AGIAZQA0ADWAHIAfABCgCIAI4ASYAlgCdAFEAUoAqACqAFcALcAXQBfADFAGUAZoA2ADdAHIAc4A7gDwAHoAP0AgACBgEGAQgAhoBFAEYAJSASwBLgCaAE6AKGAUYBSQCtAK6AXABcwDAAMIAYgAygBpgDVAHOAOuAdoB3gDxAHsAPiAfgB_AEDgIMAhABEACJAEUgIsAi8BHAEdgJKAkwBKgCWgE4gJ0AngBQQChgFLAKaAVcArIBXwC0gF1AL0AXyAwADAgGEAMUAY0AzQBnQDTgG4AN-AcIA4gBzQDqgHXAOyAdsA9AB6oD3gPiAfUA_YCBQEGAITAQsAhiBEoETAIqAReAjUBHsCRAJFATUAnQBQ4CjAFLAKfAWGAssBZ4C2AFxALzAX8AwEBgYDFAGLAMZAZYBN6CcAJyQTmBOqCdgJ4gTzAnsEGoAAABQSA6AAsACoAIIAZABqADwAIgATAAqgB6AD8AIQAQwAlgBNADvgHsAfEA_AD9AIoARcAkoBQQCrgGKANwAcQBIgChwFsALzCABwASADnAIOAj0BIoCnwGLDoEgACwAKgAgABdADEANQAeABEACYAFUALoAYgAzAB6AD8AIYASwAmgBRgDKAHeAPaAfgB-wEUARcAjoBQQCrgF6AMUAbgA4gCLwEiAKHAWwAvMBlg4AUAA8AC4AJAAfgDnAHdAQcBCAEegJFAYsQgGgALABcADEAGoATAAqgBiAD0AO8AigBQQCrgGKIAAgBzgI9JQEgAFgAxAB4AEQAJgAVQAxACGAFGAO8AfgBVwDFAImAReAkQBbAC8yQAYAC4A7gCDgI9ASKAxYpAeAAWABUAEEAMQA1AB4AEQAJgAUgAqgBiADMAH4AQwAowBlADvgH4AfoBFgCOgFBAKuAYoA3ACJgEXgJEAUOAtgBeYDLCgAwAC4AJABzgDuAIOAXUA14B2wEegJFAU-AxYAA.f_gAAAAAAAAA; _cs_c=0; _cs_id=358146a4-c53b-ae6b-b449-cf1d1a1a6808.1708503661.1.1708503661.1708503661.1.1742667661665.1; _scid=73379352-cef1-410d-9bdf-61dd5092f1c6; _scid_r=73379352-cef1-410d-9bdf-61dd5092f1c6; LPVID=VkMjljOGU1NWZkZjgwNmFj; LPSID-2422064=5rvlVPbhQ1mQD0qn2UqvMA; _ga_S0T2DJJFZM=GS1.1.1708503661.1.1.1708503672.0.0.0; _gcl_au=1.1.271438317.1712754814; sp_landing=https%3A%2F%2Fopen.spotify.com%2F%3Fsp_cid%3Da7a2199dd56676b2e95555c63580cd1f%26device%3Ddesktop; sss=1; _ga_ZWG1NSHWD8=GS1.1.1716277743.2.0.1716277743.0.0.0; OptanonConsent=isGpcEnabled=0&datestamp=Tue+May+21+2024+09%3A49%3A03+GMT%2B0200+(Mitteleurop%C3%A4ische+Sommerzeit)&version=202309.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=9a36c1fc-b857-4ef2-b656-435b27aa7cea&interactionCount=1&landingPath=NotLandingPage&groups=s00%3A1%2Cf00%3A1%2Cm00%3A1%2Ct00%3A1%2Ci00%3A1%2CV2STACK3%3A1%2CV2STACK11%3A1%2CV2STACK20%3A1%2Cf11%3A1%2CBG181%3A1&geolocation=DE%3BNW&AwaitingReconsent=false; _ga=GA1.2.1049815781.1708503661; _gid=GA1.2.1842480047.1716277743; _gat_UA-5784146-31=1
"
player: mpris
host: lyricsapi.vercel.app
ignoreErrors: true
timerInterval: 200
updateInterval: 2000

### Style settings ###
style:
  hAlignment: center
  before:
    background: ""
    foreground: "#4C566A"
    bold: true
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: false
  current:
    background: ""
    foreground: "#D8DEE9"
    bold: true
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: false
  after:
    background: ""
    foreground: "#81A1C1"
    bold: false
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: false

### Pipe settings ###
pipe:
  # Maximum line length. 0 - unlimited.
  length: 0
  # How to handle overflowing strings. Possible values: word, none, ellipsis.
  overflow: word

### MPRIS settings ###
mpris:
  # Whitelist of MPRIS players. First available is used if empty.
  players: [spotify_player]

#local:
#  folder: "~/.lyrics"
